apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: 1stdocker
    image: dishaparikh98/1stdocker:Latest
    ports:
    - name: nodejs-port
      containerPort: 3000
